### ISSUE TITLE
get_file and get_artifact doesn't support non-textual format like image

### ISSUE THREAD

**Issue by yogeshVU** [webgme/bindings#15]
I would like to retrieve an asset(image) stored in the attribute of an object. I am trying to use the python binding's get_file()  function. However, its not able to retreive the asset and get's an error
`get_file` works when the file format is a document. but fails when the file format is an image, so not sure if there is a proper way to access the image asset format

One get's following error when using get_file:
```
2020-09-08T15:43:59.277Z - error: [gme:bin:coremq_server:CoreZMQ] res 
{ err: 
   { message: 'URI malformed',
     type: 'URIError',
     stack: 'URIError: URI malformed\n    at decodeURIComponent (<anonymous>)\n    at Object.uint8ArrayToString (',
     req: { name: 'getFile', args: [Array], type: 'plugin' } },
  res: null }
```

**Comment by mnag1124** [comment]
This feature would be good to have and like I  pointed out in [this issue](https://github.com/webgme/bindings/issues/16) it will be good to know if any of the api calls  is not supported in python plugin

**Comment by kecso** [comment]
just went through on our code-base and I was wrong. on the plugin API it was never supported to download binary files.
I will add this functionality as a new function to the webgme-engine, and then populate to the bindings so it can use it as well...
(the source of my confusion is that the blobClient is easily accessible in javascript, therefore no-one requested this functionality earlier...)

**Comment by yogeshVU** [comment]
I guess this would also apply to the setter function call of the above methods as well.
