### ISSUE TITLE
Error check needs a minor correction 

### ISSUE THREAD

**Issue by mnag1124** [webgme/bindings#21]
In  [this line](https://github.com/webgme/bindings/blob/master/src/corezmq.js#L877) ,
the code should be

`if (!address && err.message.indexOf('Address already in use') > -1) {`

Note: `already` is missing.

Due to this the code does not make multiple attempts to connect with other ports and fails at first instance  there are concurrent plugin invocations.

**Comment by kecso** [comment]
Could you please check your environment? (OS, nodejs, zeromq version, bindings versions)
I just redid all our testing and the error I am getting is 'Address in use'.
